tasks:
  - name: Install and Build
    init: yarn install && yarn build
    command: yarn run dev
  - name: Docker
    init: docker build .
  - name: Rust tools
    init: |
      cargo install --locked cargo-outdated
      rustup component add clippy
      sudo apt update -y
      sudo ypt upgrade -y
      sudo apt install xsel -y
    command: cargo outdated -R

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8080
    onOpen: open-browser

vscode:
  extensions:
    - bierner.markdown-preview-github-styles
    - sndst00m.markdown-github-dark-pack

github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false
