[package]
name = "plantetb-syntax-highligher"
version = "0.1.0"
authors = ["Christof Weickhardt <christof@weickhardt.ch"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
log = "0.4.14"
strum = "0.23.0"   
strum_macros = "0.23.1" 
serde = "1.0.131" 
serde_derive = "1.0.131"  
wasm-bindgen = "0.2.78" 
wasm-logger = "0.2.0"
wee_alloc = { version = "0.4.5", optional = true }
yew = "0.19" 
anyhow = "1.0.51"   

[dev-dependencies]
wasm-bindgen-test = "0.3.28"

[dependencies.web-sys]
version = "0.3.55"
features = [
  'KeyboardEvent',
  'Document',
  'Element',
  'HtmlElement',
  'Node',
  'Window',
]
