[package]
name = "planetbb-syntax-highligher"
version = "0.1.0"
authors = ["Christof Weickhardt <christof@weickhardt.ch"]
edition = "2021"

[profile.release]
panic = 'abort'
codegen-units = 1
opt-level = 'z'
lto = 'y'

[dependencies]
log = "0.4.16"
serde = "1.0.136" 
serde_derive = "1.0.136"  
wasm-bindgen = "0.2.80" 
wasm-logger = "0.2.0"
yew = "0.19.3"   
gloo-storage = "0.2.0"

[dev-dependencies]
wasm-bindgen-test = "0.3.30"

[dependencies.web-sys]
version = "0.3.57"
features = [
  'KeyboardEvent',
  'Document',
  'Element',
  'HtmlElement',
  'Node',
  'Window',
  'InputEvent',
  'HtmlImageElement'
]
