[package]
name = "planetb-syntax-highligher"
version = "0.1.6"
authors = ["Christof Weickhardt <christof@weickhardt.ch"]
edition = "2021"

[profile.release]
panic = 'abort'
codegen-units = 1
opt-level = 'z'
lto = 'fat'

[dependencies]
log = "0.4.17"
serde = "1.0.139" 
serde_derive = "1.0.140"  
wasm-bindgen = "0.2.81" 
wasm-logger = "0.2.0"
yew = "0.19.3"   
gloo-storage = "0.2.1"

[dev-dependencies]
wasm-bindgen-test = "0.3.31"

[dependencies.web-sys]
version = "0.3.58"
features = [
  'KeyboardEvent',
  'Document',
  'Element',
  'HtmlElement',
  'Node',
  'Window',
  'InputEvent',
  'HtmlImageElement'
]
