name: Build

on:
  push:
    branches:
      - "master"
      - "develop"
  pull_request:
    branches:
      - "*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2.3.1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"
      - name: Install yarn
        run: npm i -g yarn
      - name: Install
        run: yarn install
      - name: Build
        run: yarn build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
