name: Build

on:
  push:
    branches:
      - "develop"
  pull_request:
    branches:
      - "*"

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.5

      - name: Install qemu dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Install tools
        run: |
          wget -qO- https://github.com/thedodd/trunk/releases/latest/download/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
          rustup target add wasm32-unknown-unknown
          sudo wget -O /usr/local/bin/minify https://wilsonl.in/minify-html/bin/0.8.0-linux-x86_64
          sudo chmod +x /usr/local/bin/minify

      - name: Build
        run: ./trunk build --release

      - name: Buildah Action
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: |
            Containerfile
          platforms: linux/amd64,linux/arm64
          image: ci
