name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3.0.2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install tools
        run: |
          cargo install trunk --git https://github.com/thedodd/trunk.git
          cargo install wasm-bindgen-cli
          rustup target add wasm32-unknown-unknown
          sudo wget -O /usr/local/bin/minify https://wilsonl.in/minify-html/bin/0.8.0-linux-x86_64
          sudo chmod +x /usr/local/bin/minify
          cargo install minifier
      - name: Build
        run: trunk build --release
      - name: Upload app artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-folder
          path: dist
  docker:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Process version of the tag
        id: version
        uses: ncipollo/semantic-version-action@v1

      - uses: chrnorm/deployment-action@releases/v1
        name: Create GitHub deployment
        id: deployment
        with:
          token: "${{ github.token }}"
          target_url: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
          environment: docker-hub

      - name: Update deployment status (pending)
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          target_url: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
          state: "pending"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Download built app
        uses: actions/download-artifact@v3
        with:
          name: dist-folder
          path: dist/

      - name: Update deployment status (in_progress)
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          target_url: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
          state: "in_progress"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Build Default
        env:
          VERSION: ${{ steps.version.outputs.tag }}
        run: docker buildx build --platform=linux/amd64,linux/arm64/v8 --push --tag chweicki/planetbb-syntax-highlighter:$VERSION .

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          target_url: https://hub.docker.com/repository/docker/chweicki/planetbb-syntax-highlighter
          state: "success"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          target_url: https://hub.docker.com/repository/docker/chweicki/planetbb-syntax-highlighter
          state: "failure"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

  github-pages:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Download built app
        uses: actions/download-artifact@v3
        with:
          name: dist-folder
          path: dist/
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
          clean: true
