name: Release

on: 
  push:
    tags:
    - '*'

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Process version of the tag
      id: version
      uses: ncipollo/semantic-version-action@v1
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: avakar/create-deployment@v1
      with:
        auto_merge: true
        environment: "docker-hub"
        required_contexts: success 
      env:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
    - uses: avakar/set-deployment-status@v1
      with:
        state: in_progress
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build Default
      env:
        VERSION: ${{ steps.version.outputs.tag }}
      run: docker buildx build --platform=linux/amd64,linux/arm64/v8 --push --tag chweicki/plantetb-syntax-highlighter:$VERSION .
    - uses: avakar/set-deployment-status@v1
      with:
        state: success
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: avakar/set-deployment-status@v1
      if: failure()
      with:
        state: failure
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2.3.1
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - name: Install yarn
        run: npm i -g yarn
      - name: Install 
        run: yarn install
      - name: Build
        run: yarn build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
          clean: true